fix: Database Close before executor Close (#174)
Encountered a test flake that indicated an incorrect shutdown ordering:
```
Running tool: /usr/local/go/bin/go test -test.fullpath=true -timeout 30s -coverprofile=/var/folders/5l/z00z8zbd0dbd6lf8djdgl_000000gn/T/vscode-goPihqeC/go-code-cover github.com/ava-labs/strevm/sae -coverpkg=all

--- FAIL: TestEthGetters (0.08s)
    /Users/stephen/go/src/github.com/ava-labs/strevm/saetest/logging.go:165: [Log@TRACE] Including transaction map[block_time:5 last_settled_hash:0x002019fa13ca5ef31959c63d171aaacb7a54deafc8cb0d07ba810b73449634e2 last_settled_height:0 parent_hash:0x002019fa13ca5ef31959c63d171aaacb7a54deafc8cb0d07ba810b73449634e2 parent_height:0 sender:0x89b573E68030D1aaB75CA8B83db79c3F3ACa2950 tx_hash:0xca95edf571768d6ce0953ea34aee575e5ce2b99345108c65bde17b951e7c1dea tx_index:0] - /Users/stephen/go/src/github.com/ava-labs/strevm/sae/blocks.go:239
    /Users/stephen/go/src/github.com/ava-labs/strevm/saetest/logging.go:165: [Log@TRACE] Including transaction map[block_time:5 last_settled_hash:0x002019fa13ca5ef31959c63d171aaacb7a54deafc8cb0d07ba810b73449634e2 last_settled_height:0 parent_hash:0x002019fa13ca5ef31959c63d171aaacb7a54deafc8cb0d07ba810b73449634e2 parent_height:0 sender:0x89b573E68030D1aaB75CA8B83db79c3F3ACa2950 tx_hash:0xca95edf571768d6ce0953ea34aee575e5ce2b99345108c65bde17b951e7c1dea tx_index:0] - /Users/stephen/go/src/github.com/ava-labs/strevm/sae/blocks.go:239
    /Users/stephen/go/src/github.com/ava-labs/strevm/saetest/logging.go:165: [Log@DEBUG] Accepted block map[hash:0xc2f1761a9814095809fa32634b34c25e042f98c63232f24f4673599539709154 height:1] - /Users/stephen/go/src/github.com/ava-labs/strevm/sae/consensus.go:96
    /Users/stephen/go/src/github.com/ava-labs/strevm/saetest/logging.go:165: [Log@DEBUG] Executing block map[block_hash:0xc2f1761a9814095809fa32634b34c25e042f98c63232f24f4673599539709154 block_height:1 block_time:5 tx_count:1] - /Users/stephen/go/src/github.com/ava-labs/strevm/saexec/execution.go:85
    /Users/stephen/go/src/github.com/ava-labs/strevm/saetest/logging.go:165: [Log@DEBUG] Block execution complete map[block_hash:0xc2f1761a9814095809fa32634b34c25e042f98c63232f24f4673599539709154 block_height:1 block_time:5 gas_consumed:21000 gas_time:1970-01-01 00:00:05.000105 +0000 UTC tx_count:1 tx_hash:0xca95edf571768d6ce0953ea34aee575e5ce2b99345108c65bde17b951e7c1dea tx_index:0 wall_time:2026-02-17 16:24:35.232081 -0500 EST] - /Users/stephen/go/src/github.com/ava-labs/strevm/saexec/execution.go:195
    /Users/stephen/go/src/github.com/ava-labs/strevm/saetest/logging.go:165: [Log@TRACE] Including transaction map[block_time:5 last_settled_hash:0x002019fa13ca5ef31959c63d171aaacb7a54deafc8cb0d07ba810b73449634e2 last_settled_height:0 parent_hash:0xc2f1761a9814095809fa32634b34c25e042f98c63232f24f4673599539709154 parent_height:1 sender:0x89b573E68030D1aaB75CA8B83db79c3F3ACa2950 tx_hash:0x892b7cc1647af00a5b9a72b64040b429f6aaeb6cd6ab7efd6e2e0d32c6ebd72f tx_index:0] - /Users/stephen/go/src/github.com/ava-labs/strevm/sae/blocks.go:239
    /Users/stephen/go/src/github.com/ava-labs/strevm/saetest/logging.go:165: [Log@TRACE] Including transaction map[block_time:5 last_settled_hash:0x002019fa13ca5ef31959c63d171aaacb7a54deafc8cb0d07ba810b73449634e2 last_settled_height:0 parent_hash:0xc2f1761a9814095809fa32634b34c25e042f98c63232f24f4673599539709154 parent_height:1 sender:0x89b573E68030D1aaB75CA8B83db79c3F3ACa2950 tx_hash:0x892b7cc1647af00a5b9a72b64040b429f6aaeb6cd6ab7efd6e2e0d32c6ebd72f tx_index:0] - /Users/stephen/go/src/github.com/ava-labs/strevm/sae/blocks.go:239
    /Users/stephen/go/src/github.com/ava-labs/strevm/saetest/logging.go:165: [Log@DEBUG] Accepted block map[hash:0x23489b366ad6122db27fc687e0541dfe0fd772dde5104495ec4512da271587b2 height:2] - /Users/stephen/go/src/github.com/ava-labs/strevm/sae/consensus.go:96
    /Users/stephen/go/src/github.com/ava-labs/strevm/saetest/logging.go:165: [Log@DEBUG] Executing block map[block_hash:0x23489b366ad6122db27fc687e0541dfe0fd772dde5104495ec4512da271587b2 block_height:2 block_time:5 tx_count:1] - /Users/stephen/go/src/github.com/ava-labs/strevm/saexec/execution.go:85
    /Users/stephen/go/src/github.com/ava-labs/strevm/saetest/logging.go:165: [Log@DEBUG] Block execution complete map[block_hash:0x23489b366ad6122db27fc687e0541dfe0fd772dde5104495ec4512da271587b2 block_height:2 block_time:5 gas_consumed:21000 gas_time:1970-01-01 00:00:05.00021 +0000 UTC tx_count:1 tx_hash:0x892b7cc1647af00a5b9a72b64040b429f6aaeb6cd6ab7efd6e2e0d32c6ebd72f tx_index:0 wall_time:2026-02-17 16:24:35.2325 -0500 EST] - /Users/stephen/go/src/github.com/ava-labs/strevm/saexec/execution.go:195
    /Users/stephen/go/src/github.com/ava-labs/strevm/saetest/logging.go:165: [Log@TRACE] Including transaction map[block_time:10 last_settled_hash:0x23489b366ad6122db27fc687e0541dfe0fd772dde5104495ec4512da271587b2 last_settled_height:2 parent_hash:0x23489b366ad6122db27fc687e0541dfe0fd772dde5104495ec4512da271587b2 parent_height:2 sender:0x89b573E68030D1aaB75CA8B83db79c3F3ACa2950 tx_hash:0x2ac9ce649b5ded36755aaa7443867b8290854d9cddb106ce908ddbbb505867d2 tx_index:0] - /Users/stephen/go/src/github.com/ava-labs/strevm/sae/blocks.go:239
    /Users/stephen/go/src/github.com/ava-labs/strevm/saetest/logging.go:165: [Log@TRACE] Including transaction map[block_time:10 last_settled_hash:0x23489b366ad6122db27fc687e0541dfe0fd772dde5104495ec4512da271587b2 last_settled_height:2 parent_hash:0x23489b366ad6122db27fc687e0541dfe0fd772dde5104495ec4512da271587b2 parent_height:2 sender:0x89b573E68030D1aaB75CA8B83db79c3F3ACa2950 tx_hash:0x2ac9ce649b5ded36755aaa7443867b8290854d9cddb106ce908ddbbb505867d2 tx_index:0] - /Users/stephen/go/src/github.com/ava-labs/strevm/sae/blocks.go:239
    /Users/stephen/go/src/github.com/ava-labs/strevm/saetest/logging.go:165: [Log@DEBUG] Accepted block map[hash:0xeb9507813133d2f133bd4fd556dfa97def35aa8bf04788dff37a82cdaf64530e height:3] - /Users/stephen/go/src/github.com/ava-labs/strevm/sae/consensus.go:96
    /Users/stephen/go/src/github.com/ava-labs/strevm/saetest/logging.go:165: [Log@DEBUG] Executing block map[block_hash:0xeb9507813133d2f133bd4fd556dfa97def35aa8bf04788dff37a82cdaf64530e block_height:3 block_time:10 tx_count:1] - /Users/stephen/go/src/github.com/ava-labs/strevm/saexec/execution.go:85
    /Users/stephen/go/src/github.com/ava-labs/strevm/saetest/logging.go:165: [Log@DEBUG] Block execution complete map[block_hash:0xeb9507813133d2f133bd4fd556dfa97def35aa8bf04788dff37a82cdaf64530e block_height:3 block_time:10 gas_consumed:21000 gas_time:1970-01-01 00:00:10.000315 +0000 UTC tx_count:1 tx_hash:0x2ac9ce649b5ded36755aaa7443867b8290854d9cddb106ce908ddbbb505867d2 tx_index:0 wall_time:2026-02-17 16:24:35.233063 -0500 EST] - /Users/stephen/go/src/github.com/ava-labs/strevm/saexec/execution.go:195
    /Users/stephen/go/src/github.com/ava-labs/strevm/saetest/logging.go:165: [Log@TRACE] Including transaction map[block_time:10 last_settled_hash:0x23489b366ad6122db27fc687e0541dfe0fd772dde5104495ec4512da271587b2 last_settled_height:2 parent_hash:0xeb9507813133d2f133bd4fd556dfa97def35aa8bf04788dff37a82cdaf64530e parent_height:3 sender:0x89b573E68030D1aaB75CA8B83db79c3F3ACa2950 tx_hash:0x17f9a03809fa66fd9cd61e867f8e3c758efd384fdfb51ee835fceda0a16341b7 tx_index:0] - /Users/stephen/go/src/github.com/ava-labs/strevm/sae/blocks.go:239
    /Users/stephen/go/src/github.com/ava-labs/strevm/saetest/logging.go:165: [Log@TRACE] Including transaction map[block_time:10 last_settled_hash:0x23489b366ad6122db27fc687e0541dfe0fd772dde5104495ec4512da271587b2 last_settled_height:2 parent_hash:0xeb9507813133d2f133bd4fd556dfa97def35aa8bf04788dff37a82cdaf64530e parent_height:3 sender:0x89b573E68030D1aaB75CA8B83db79c3F3ACa2950 tx_hash:0x17f9a03809fa66fd9cd61e867f8e3c758efd384fdfb51ee835fceda0a16341b7 tx_index:0] - /Users/stephen/go/src/github.com/ava-labs/strevm/sae/blocks.go:239
    /Users/stephen/go/src/github.com/ava-labs/strevm/saetest/logging.go:165: [Log@DEBUG] Accepted block map[hash:0x46ccb42ac525750af4a9011844fe75dd121dafdb28bcaf8faf526fd10baa63b9 height:4] - /Users/stephen/go/src/github.com/ava-labs/strevm/sae/consensus.go:96
    /Users/stephen/go/src/github.com/ava-labs/strevm/saetest/logging.go:165: [Log@DEBUG] Executing block map[block_hash:0x46ccb42ac525750af4a9011844fe75dd121dafdb28bcaf8faf526fd10baa63b9 block_height:4 block_time:10 tx_count:1] - /Users/stephen/go/src/github.com/ava-labs/strevm/saexec/execution.go:85
    /Users/stephen/go/src/github.com/ava-labs/strevm/saetest/logging.go:165: [Log@DEBUG] Block execution complete map[block_hash:0x46ccb42ac525750af4a9011844fe75dd121dafdb28bcaf8faf526fd10baa63b9 block_height:4 block_time:10 gas_consumed:21000 gas_time:1970-01-01 00:00:10.00042 +0000 UTC tx_count:1 tx_hash:0x17f9a03809fa66fd9cd61e867f8e3c758efd384fdfb51ee835fceda0a16341b7 tx_index:0 wall_time:2026-02-17 16:24:35.293096 -0500 EST] - /Users/stephen/go/src/github.com/ava-labs/strevm/saexec/execution.go:195
    /Users/stephen/go/src/github.com/ava-labs/strevm/saetest/logging.go:165: [Log@FATAL] Block execution failed; see emergency playbook map[block_hash:0x46ccb42ac525750af4a9011844fe75dd121dafdb28bcaf8faf526fd10baa63b9 block_height:4 block_time:10 error:closed playbook:https://github.com/ava-labs/strevm/issues/28 tx_count:1] - /Users/stephen/go/src/github.com/ava-labs/strevm/saexec/execution.go:73
    /Users/stephen/go/src/github.com/ava-labs/strevm/saetest/logging.go:165: [Log@DEBUG] shutting down gossip map[] - /Users/stephen/go/pkg/mod/github.com/ava-labs/avalanchego@v1.14.2-0.20260123184805-18c4dbe2714e/network/p2p/gossip/gossip.go:630
    /Users/stephen/go/src/github.com/ava-labs/strevm/saetest/logging.go:165: [Log@DEBUG] shutting down gossip map[] - /Users/stephen/go/pkg/mod/github.com/ava-labs/avalanchego@v1.14.2-0.20260123184805-18c4dbe2714e/network/p2p/gossip/gossip.go:630
FAIL
coverage: 12.3% of statements in all
FAIL	github.com/ava-labs/strevm/sae	13.800s
FAIL
```


```golang
xdb, err := cfg.Hooks.ExecutionResultsDB(
	filepath.Join(snowCtx.ChainDataDir, "sae_execution_results"),
)
if err != nil {
	return nil, fmt.Errorf("%T.ExecutionResultsDB(%q): %v", cfg.Hooks, snowCtx.ChainDataDir, err)
}
vm.toClose = append(vm.toClose, xdb.Close)

...

exec, err := saexec.New(
	lastExecuted,
	vm.blockSource,
	chainConfig,
	db,
	xdb,
	cfg.TrieDBConfig,
	vm.hooks(),
	snowCtx.Log,
)
if err != nil {
	return nil, fmt.Errorf("saexec.New(...): %v", err)
}
vm.exec = exec
vm.toClose = append(vm.toClose, exec.Close)
```

`xdb.Close` was being called before `exec.Close`, which caused the
executor to encounter a FATAL `error:closed`.