test: fix `TestAcceptBlock` flake (#139)
Closes #133. 

Occasionally this test will fail with 

```
Error: Should be zero, but was 2
Messages: initial in-memory block count
```

Under CI, previous tests' finalizers can take >100ms to run, which does
not give the GC adequate time to run -- this gives the GC ample time.

---------

Signed-off-by: Jonathan Oppenheimer <147infiniti@gmail.com>